[package]
name = "stablekeepr"
version = "0.1.0"
edition = "2021"

[dependencies]
comfyui_workflow_parser = { path = "src/comfy/comfyui_workflow_parser" }
config = "0.14.0"
serde = "1.0.130"
serde_derive = "1.0.203"
dirs-next = "2.0.0"
serde_json = "1.0.118"
walkdir = "2.5.0"
png = "0.17.13"
